class ChecklistItem < ApplicationRecord
  belongs_to :trip
  belongs_to :item, optional: true  # Pour les items prédéfinis
  has_many :likes, dependent: :destroy

  validates :name, presence: true
  validates :checked, inclusion: { in: [true, false] }, allow_nil: false
  validates :ai_data, presence: true, if: :ai_generated?

  # Check if item was generated by AI
  def ai_generated?
    !ai_data.nil? && ai_data.present?
  end
end
